version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: himanshus10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init script

  user:
    build:
      context: . # Set context to the root of the project
      dockerfile: USER/Dockerfile # Specify the path to the Dockerfile
    ports:
      - "8041:8041"
    depends_on:
      - db

  task:
    build:
      context: . # Set context to the root of the project
      dockerfile: TASK/Dockerfile # Specify the path to the Dockerfile
    ports:
      - "8042:8042"
    depends_on:
      - db

  notify:
    build:
      context: . # Set context to the root of the project
      dockerfile: NOTIFY/Dockerfile # Specify the path to the Dockerfile
    ports:
      - "8043:8043"
    depends_on:
      - db

  ui:
    build:
      context: . # Set context to the root of the project
      dockerfile: UI/Dockerfile # Specify the path to the Dockerfile
    ports:
      - "8040:8040"
    depends_on:
      - db

volumes:
  db_data:
